apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app-deployment
spec:
  replicas: 1
  selector: # every deployment watches all the pods which are under this deployment
    matchLabels: # in order to specify the pods which will be controlled by the deployment are specified inside this spec
      # this must be same as the labels in the pods
      app: first-app-pod
      tier: backend
  template: # This template always contains details of the POD i.e Kind: Pod
    metadata:
      labels: # a pod can have multiple labels like here we have given 2, you can name it whatever you want.
        app: first-app-pod
        tier: backend
    spec:
      containers: # So we also need to specify the container configurations in the pod
      # now you can have multiple containers in the same pods thats why it is represented by - i.e list 
      - name: first-app-container
        image: sourishjana/demoimages:v1 #image name of dockerhub

