apiVersion: v1
kind: Service
metadata:
  name: app-service 
  labels: 
    environment: dev
spec:
  selector: 
    app: first-app-pod
    tier: backend
  ports: 
    - protocol: TCP 
      port: 80
      targetPort: 8080 
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app-deployment
  labels: 
    environment: dev
spec:
  replicas: 3
  selector: 
    matchLabels: 
      app: first-app-pod
      tier: backend
  template: 
    metadata:
      labels: 
        app: first-app-pod
        tier: backend
    spec:
      containers: 
      - name: first-app-container
        image: sourishjana/demoimages:v1 
        livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 10

