apiVersion: v1
kind: Service
metadata:
  name: frontend-service-bookapp
  namespace: bookapp
spec:
  selector:
    app: frontend
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8080