apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc-bookapp
  namespace: bookapp
spec:
  volumeName: mssql-pv-bookapp
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
