apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: task
  template:
    metadata:
      labels:
        app: task
    spec:
      containers:
        - name: task
          image: sourishjana/demoimages:task1
          env:
            - name: PORT 
              valueFrom:
                configMapKeyRef:
                  name: config-map-mc
                  key: taskPort 
            - name: AUTH_SERVICE 
              valueFrom:
                configMapKeyRef:
                  name: config-map-mc
                  key: userRoute 
            - name: TASKS_FOLDER 
              valueFrom:
                configMapKeyRef:
                  name: config-map-mc
                  key: folder 